### PR TITLE
allow options on "ask" for userInteraction

### PR DESCRIPTION
**Pull request by squallstar**
Ref. https://github.com/Fliplet/fliplet-studio/issues/4181

```js
var pushWidget = Fliplet.Widget.get('PushNotifications');

// mark the allow popup as seen and skip it
pushWidget.ask({ userInteraction: true }).then(function (subscriptionId) {
  // user pressed allow and has been registered
}).catch(function (err) {
  // contains code and message
});
```

### CODE REVIEW

**Comment by tonytlwu** [comment]
@squallstar Have you tested this?

**Comment by tonytlwu** [comment]
@squallstar Is this ready?

**Comment by squallstar** [comment]
@tonytlwu needs retesting because of a manual merge I had to do.

**Comment by tonytlwu** [comment]
Bump

**Comment by squallstar** [comment]
Ready on staging for testing.

**Comment by tonytlwu** [comment]
## Testing notes

1. Launch any iOS native app.
1. If the user is asked to allow or subscribe to notifications via the Fliplet custom UI, don't allow it.
1. Open the **About this app** overlay.
1. Subscribe to notifications
1. Expected: The iOS native popup appears, asking the user to accept push notifications. The Fliplet custom UI doesn't appear.

**Pull request merged**
